services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -s -k https://localhost:9200 | grep 'missing authentication credentials' || exit 1"]
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}