metricbeat.modules:
- module: system
  metricsets:
    - cpu             
    - load            
    - memory
    - process
    - process_summary
  enabled: true
  period: 15s
  processes: ['.*']
  hostfs: "/hostfs"
  cpu.metrics:  ["percentages","normalized_percentages"]
  core.metrics: ["percentages"]
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 15s
  enabled: true

output.elasticsearch:
  hosts: 'https://elasticsearch:9200'
  username: 'elastic'
  password: '${ELASTICSEARCH_PASSWORD}'
  ssl.certificate_authorities: /usr/share/metricbeat/config/certs/ca/ca.crt